### ISSUE TITLE
Refusal to rip (no musicbrainz reference)

### ISSUE THREAD

**Issue by storrgie** [thomasvs/morituri#115]
I'd excpected this to rip, however it just ejects the disk every time I attempt:

[morituri-uninstalled] [agd@enyo morituri]$ rip cd -d /dev/sr0 rip --offset 667
Checking device /dev/sr0
CDDB disc id: 8b0c390c                        
MusicBrainz disc id aIQkgdYhYhlJKZbajBN0ymPVQYs-
MusicBrainz lookup URL https://musicbrainz.org/cdtoc/attach?toc=1+12+234882+150+37721+54783+92396+97928+122698+138323+155762+163191+183399+216831+228071&tracks=12&id=aIQkgdYhYhlJKZbajBN0ymPVQYs-
Disc duration: 00:52:09.760, 12 audio tracks
Continuing without metadata
Submit this disc to MusicBrainz at the above URL.

FreeDB identifies disc as Optina Pustyn Male Choir of St. Petersburg / Orthodox Chants from Russia

**Comment by ArchangeGabriel** [comment]
You might either configure morituri to rip it using the CDDB information, or fill MusicBrainz database with the informations, and then rip it.

**Comment by storrgie** [comment]
Is there a better way to do that, rather than using the -U arg?

rip cd rip -o 667 -U

**Comment by ArchangeGabriel** [comment]
Yes. As I’ve said, you must either install the python CDDB module necessary for Morituri to rip using FreeDB (cddb-py on ArchLinux for instance) or fill add your CD manually in the DB at musicbrainz.org.

**Comment by thomasvs** [comment]
morituri doesn't actually pull any track information from cddb.  This is by choice - data in cddb is terrible quality, inconsistent, and not properly curated.

Musicbrainz is excellent quality, and a submission is immediately available to use for morituri, contrary to cddb.

So yes, simply click the link and submit the information.

**Comment by storrgie** [comment]
@thomasvs Thanks for the clarification. I had the python-cddb installed already and it seemed to pull some information to provide to the screen but there were no cli options other than -U that would prevent an attempt to use musicbrainz.

**Comment by l-mb** [comment]
The web interface for Musicbrainz to import data from FreeDB is horrible quality. I'd rather have semi-accurate metadata on my rips than not have any at all, or be forced to spend minutes on every CD I rip.

Has anyone developed a patch already to fall back to using FreeDB data?
