### ISSUE TITLE
Not present at MusicBrainz -> Not ripping

### ISSUE THREAD

**Issue by TJFOE** [thomasvs/morituri#128]
Hi,

starting a rip with:

rip cd rip --offset 48 --profile="wav"  --track-template='%A - %d/%t. %a - %n'  --disc-template= '%A - %d/%A - %d'

or

rip cd rip --offset 48 --profile="wav"

stops the ripping process, if the CD doesn't exist at MusicBrainz. It is not possible to rip the disc. Like track01.wav, track02.wav ...

Regards
Thomas

----------
Output:
----------
Disc duration: 01:11:55.000, 16 audio tracks
Error: NotFoundException(ResponseError(),)
Continuing without metadata
Submit this disc to MusicBrainz at the above URL.

FreeDB identifies disc as ...

**Comment by thomasvs** [comment]
It is possible.  You either add the disc to musicbrainz and redo it, or you use --unknown.
