### ISSUE TITLE
/dev/sr0 vs. /dev/bsg:0:0:0:0

### ISSUE THREAD

**Issue by lutzbickhardt** [thomasvs/morituri#51]
this is driving me crazy!
on all older kernels I have here my USB-CD-drive is /dev/srX.
on a newer kernel 3.8 (Ubuntu and Debian) it evaluates as /dev/bsg/0:0:0:0

I cannot make morituri run with: rip offset find -d /dev/bsg/0:0:0:0

some output:

$ dmesg
[   45.901224] usb usb1: usb wakeup-resume
[   45.901284] usb usb1: usb auto-resume
[   45.901313] hub 1-0:1.0: hub_resume
[   45.901371] hub 1-0:1.0: port 1: status 0101 change 0001
[   46.004052] hub 1-0:1.0: state 7 ports 1 chg 0002 evt 0000
[   46.004116] hub 1-0:1.0: port 1, status 0101, change 0000, 12 Mb/s
[   46.109486] usb 1-1: new high-speed USB device number 2 using musb-hdrc
[   46.229131] usb 1-1: default language 0x0409
[   46.229587] usb 1-1: udev 2, busnum 1, minor = 1
[   46.229607] usb 1-1: New USB device found, idVendor=14cd, idProduct=6600
[   46.229623] usb 1-1: New USB device strings: Mfr=1, Product=3, SerialNumber=2
[   46.229638] usb 1-1: Product: USB 2.0  IDE DEVICE  
[   46.229651] usb 1-1: Manufacturer: Super Top 
[   46.229665] usb 1-1: SerialNumber: \xffffffe2\xffffff80\xffffffa0\xffffffe2\xffffff80\xffffffa0\xffffffe2\xffffff80\xffffffa0\xffffffe2\xffffff80\xffffffa0\xffffffe2\xffffff80\xffffffa0\xffffffe2\xffffff80\xffffffa0\xffffffe2\xffffff80\xffffffa0\xffffffe2\xffffff80\xffffffa0\xffffffe2\xffffff80\xffffffa0\xffffffe2\xffffff80\xffffffa0
[   46.230354] usb 1-1: usb_probe_device
[   46.230381] usb 1-1: configuration #1 chosen from 1 choice
[   46.234147] usb 1-1: adding 1-1:1.0 (config #1, interface 0)
[   46.234652] usb-storage 1-1:1.0: usb_probe_interface
[   46.234689] usb-storage 1-1:1.0: usb_probe_interface - got id
[   46.238627] usb-storage 1-1:1.0: Quirks match for vid 14cd pid 6600: 20
[   46.240131] scsi0 : usb-storage 1-1:1.0
[   46.241224] hub 1-0:1.0: state 7 ports 1 chg 0000 evt 0002
[   46.241293] hub 1-0:1.0: port 1 enable change, status 00000503
[   47.246064] scsi 0:0:0:0: CD-ROM            TEAC     CD-224E          H.9A PQ: 0 ANSI: 0

ubuntu@ubuntu-armhf:~$ lsusb
Bus 001 Device 002: ID 14cd:6600 Super Top USB 2.0 IDE DEVICE
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

ubuntu@ubuntu-armhf:~$ sudo lshw -short
# H/W path  Device  Class      Description

```
              system     TI AM335x BeagleBone
```

/0                bus        Motherboard
/0/0              processor  cpu
/0/1              memory     242MiB System memory
/1        scsi0   storage  
/2        eth0    network    Ethernet interface
ubuntu@ubuntu-armhf:~$ ls /dev/bsg/
0:0:0:0

ubuntu@ubuntu-armhf:~$ sudo rip offset find -d /dev/bsg/0:0:0:0
Checking device /dev/bsg/0:0:0:0
eject: CD-ROM tray close command failed: Inappropriate ioctl for device
rip: error: cannot read CD from drive.
cdrdao says:
/dev/bsg/0:0:0:0: SCSI command Inquiry (0x12) failed: Invalid argument.
Inquiry command failed on "/dev/bsg/0:0:0:0"
Inquiry failed and no driver id is specified.
Please use option --driver to specify a driver id.
Cannot setup device /dev/bsg/0:0:0:0.

ubuntu@ubuntu-armhf:~$ sudo sg_start --stop --eject /dev/bsg/0:0:0:0
start stop unit:  Fixed format, current;  Sense key: Unit Attention
 Additional sense: Not ready to ready change, medium may have changed
unit attention
START STOP UNIT command failed 

ubuntu@ubuntu-armhf:~$ ls /dev/sr*
ls: cannot access /dev/sr*: No such file or directory

Do I use wrong syntax, or is /dev/bsg/\* not supported yet?
Pls. help!

**Comment by jeanpaulrh** [comment]
I have a problem ripping a cd with morituri giving up on the second to last track.
It's the first cd which gives me this kind of problem and I've ripped around 15 cds so far, but the drive is new and I still can return it if its ripping capabilities are poor.
Its offset it's 6, so it seems a little bit different from the case of the OP.
What test do you suggest (a part from ripping some more cd in the next few days which I'm doing anyway)?
Thanks a lot,

          Gianpaolo
