### ISSUE TITLE
Message: pygobject_register_sinkfunc is deprecated (GstObject)

### ISSUE THREAD

**Issue by nihilistcat** [thomasvs/morituri#64]
Get this message on Arch Linux x64, not sure if it's something on my end or a bug in morituri?

Checking device /dev/cdrom
eject: CD-ROM tray close command failed: Input/output error
Trying read offset 6 ...  
*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
Trying read offset 48 ...  
Offset of device is likely 48, confirming

**Comment by nsajko** [comment]
http://stackoverflow.com/questions/9750317/python-gstreamer-plugins could be relevant to the deprecation warning and offers a solution (decodebin → decodebin2).

**Comment by ace214** [comment]
I also got this error, but my offset according to EAC and the AccurateRip website was 6. Morituri never properly confirmed the offset. Should I open a new bug?

**Comment by cbanowsky** [comment]
I believe so. Can you run it again?
