### ISSUE TITLE
Ask which release to use if DiscID returns several matches

### ISSUE THREAD

**Issue by Freso** [thomasvs/morituri#9]
If the CD TOC corresponds to >1 match on MusicBrainz, ask which one to use if the --release-id wasn't specified.

Something like [isrcsubmit's Disc.getRelease method](https://github.com/JonnyJD/musicbrainz-isrcsubmit/blob/master/isrcsubmit.py#L489) perhaps?

**Comment by tlc** [comment]
I'd suggest a configured country preference.
default-country: US
