### ISSUE TITLE
Make clearer python(2)-pycdio is needed to store drive offset and caching behaviour (and incidentally create config file)

### ISSUE THREAD

**Issue by neitsab** [thomasvs/morituri#96]
It took me quite a while to figure out why no configuration file would be created after running both `rip offset find` and `rip drive analyze` commands. Debug logs were of no help and neither was `stout/stderr` output. 

I had to dig within Github issues to find the open #71 and closed #4, where in the latter @supermanvelo explains that optional dependency `pycdio` is required for drive offset and caching behaviour to be stored in the config file, incidentally creating it. I had omitted to install it on purpose because [README.md#Requirements](https://github.com/thomasvs/morituri/blame/master/README.md#L34) only states:
> - pycdio, for drive identification (optional)

which sounded like something I wouldn't need (although at this point I didn't have much info about what the `rip drive list` command did anyway).

Drive offset and caching behaviour sound to me as a prime features of a CD ripper aiming at "accuracy over speed"; not storing them, and thus requiring users to remember and mention them everytime (which doesn't seem to be possible for caching behaviour) because an **optional dependency** labeled for drive identification is absent, deters from using this excellent software, for the sharing of which I thank you.

So, please consider rephrasing the description of `pycdio` dependency to make it explicit that albeit optional, it is ***required*** for offset and caching registration, or add a note in [Getting started](https://github.com/thomasvs/morituri#getting-started) instructions that for `rip cd rip  # uses the offset from configuration file` to work this optdepend is needed.

Also, program output could be used to point to the issue: if running `rip offset find` with `pycdio` installed prints:
`Adding read offset to configuration file.`
running it *without* `pycdio` installed could say:
`Not adding read offset to configuration file because pycdio is not installed`

Thanks!

**Comment by Freso** [comment]
This can probably be closed now?
